// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1BFKxhNuUyUKiFZ23tigWT2p0X9pgvNY',
    appId: '1:305403273162:web:85cd97872886cdb9377933',
    messagingSenderId: '305403273162',
    projectId: 'foodexpiry6709',
    authDomain: 'foodexpiry6709.firebaseapp.com',
    storageBucket: 'foodexpiry6709.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANvUUtuy29KTEAFp2aA8NEjpEDuZmB950',
    appId: '1:305403273162:android:ce74d9d778eda71d377933',
    messagingSenderId: '305403273162',
    projectId: 'foodexpiry6709',
    storageBucket: 'foodexpiry6709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgRDpNqhXTxFMOQfJ1N70-2R2Ygew2nVo',
    appId: '1:305403273162:ios:b5014685618bf646377933',
    messagingSenderId: '305403273162',
    projectId: 'foodexpiry6709',
    storageBucket: 'foodexpiry6709.firebasestorage.app',
    iosBundleId: 'com.rabindra.foodtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgRDpNqhXTxFMOQfJ1N70-2R2Ygew2nVo',
    appId: '1:305403273162:ios:e08095258a6620c8377933',
    messagingSenderId: '305403273162',
    projectId: 'foodexpiry6709',
    storageBucket: 'foodexpiry6709.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1BFKxhNuUyUKiFZ23tigWT2p0X9pgvNY',
    appId: '1:305403273162:web:168b8d12e1a62ce9377933',
    messagingSenderId: '305403273162',
    projectId: 'foodexpiry6709',
    authDomain: 'foodexpiry6709.firebaseapp.com',
    storageBucket: 'foodexpiry6709.firebasestorage.app',
  );

}