// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfz6mgfV2J4LRYEOHVY0jU57sr4s2kSs',
    appId: '1:186092571144:web:368a5e757bacf16bcf5fbd',
    messagingSenderId: '186092571144',
    projectId: 'food-expiry-tracker-dddf6',
    authDomain: 'food-expiry-tracker-dddf6.firebaseapp.com',
    storageBucket: 'food-expiry-tracker-dddf6.firebasestorage.app',
    measurementId: 'G-YKEVBTND7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Nt2GaPk6pcq62Y81r8SVx8xuEoJrzX4',
    appId: '1:186092571144:android:64d28cc0365d0df8cf5fbd',
    messagingSenderId: '186092571144',
    projectId: 'food-expiry-tracker-dddf6',
    storageBucket: 'food-expiry-tracker-dddf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTsE6n4a4wYlzVAA7sUHwqFmX6WOyH3Ns',
    appId: '1:186092571144:ios:e80ac7f7612222f7cf5fbd',
    messagingSenderId: '186092571144',
    projectId: 'food-expiry-tracker-dddf6',
    storageBucket: 'food-expiry-tracker-dddf6.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTsE6n4a4wYlzVAA7sUHwqFmX6WOyH3Ns',
    appId: '1:186092571144:ios:e80ac7f7612222f7cf5fbd',
    messagingSenderId: '186092571144',
    projectId: 'food-expiry-tracker-dddf6',
    storageBucket: 'food-expiry-tracker-dddf6.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABfz6mgfV2J4LRYEOHVY0jU57sr4s2kSs',
    appId: '1:186092571144:web:488924da47c33148cf5fbd',
    messagingSenderId: '186092571144',
    projectId: 'food-expiry-tracker-dddf6',
    authDomain: 'food-expiry-tracker-dddf6.firebaseapp.com',
    storageBucket: 'food-expiry-tracker-dddf6.firebasestorage.app',
    measurementId: 'G-9L3JT02KPT',
  );
}
